/*
 *  Copyright (c) 2015 Agung Pramono <agungpermadi13@gmail.com || www.github.com/agung pramono>.
 *  All rights reserved.
 * 
 * Silahkan digunakan dengan bebas / dimodifikasi
 * Dengan tetap mencantumkan nama @author dan Referensi / Source
 * Terima Kasih atas Kerjasamanya.
 * 
 *  MainMenu.java
 * 
 *  Created on Dec 7, 2015, 10:03:34 PM
 */
package com.agung.pos.ui;

import com.agung.pos.Main;
import com.agung.pos.entity.security.Kasir;
import com.agung.pos.ui.master.MasterData;
import com.agung.pos.ui.report.LaporanPendapatan;
import com.agung.pos.ui.report.LaporanPenjualanHarian;
import com.agung.pos.ui.report.PanelCetakNota;
import com.agung.pos.ui.security.MasterUser;
import com.agung.pos.ui.transaksi.PanelPenjualan;
import java.awt.Frame;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JTabbedPane;

/**
 *
 * @author agung
 */
public class MainMenu extends javax.swing.JFrame {

    
    private Integer indexTabs = -1;
    private Kasir kasir;
    public MainMenu() {
        initComponents();
        setTitle(".: Aplikasi Penjualan Barang v.0.1 by agungpermadi13@gmail.com:.");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    public JTabbedPane getMainTabedPane(){
        return mainTabbedPane;
    }
    
    private int getComponentIndexByName(String panelName){
        return mainTabbedPane.indexOfTab(panelName);
    }
    
    private void setSelectedPanel(String panelName){
        mainTabbedPane.setSelectedComponent(mainTabbedPane.getComponentAt(getComponentIndexByName(panelName)));
    }
    
    public JProgressBar getProgress(){
        return progresBar;
    }
    
    public JLabel getStatus(){
        return lblStatus;
    }
    
    public void initSecurity(){
        lblUsername.setText("<html><b> Username : "+Main.getKasir().getUserName()+"</b></html>");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTransaksi = new javax.swing.JButton();
        btnMaster = new javax.swing.JButton();
        btnLapHarian = new javax.swing.JButton();
        btnLapPendapatan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        mainTabbedPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        progresBar = new javax.swing.JProgressBar();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCetakNota = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTransaksi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/purchase.png"))); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnMaster.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/data.png"))); // NOI18N
        btnMaster.setText("Data Master");
        btnMaster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterActionPerformed(evt);
            }
        });

        btnLapHarian.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLapHarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/series.png"))); // NOI18N
        btnLapHarian.setText("Laporan Harian");
        btnLapHarian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapHarian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLapHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapHarianActionPerformed(evt);
            }
        });

        btnLapPendapatan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLapPendapatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/document_ok.png"))); // NOI18N
        btnLapPendapatan.setText("Laporan Pendapatan");
        btnLapPendapatan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapPendapatan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLapPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPendapatanActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logout.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnTutup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/error.png"))); // NOI18N
        btnTutup.setText("Tutup");
        btnTutup.setDoubleBuffered(true);
        btnTutup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTutup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMaster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLapHarian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLapPendapatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLapHarian, btnTransaksi});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTutup)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(btnMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(btnLapPendapatan)
                    .addComponent(btnLapHarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLapHarian, btnLapPendapatan, btnLogout, btnMaster, btnTransaksi, btnTutup});

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsername.setText("Username : AA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progresBar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progresBar, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Record Transaksi");

        menuCetakNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/child/printer.png"))); // NOI18N
        menuCetakNota.setText("Cetak Nota");
        menuCetakNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCetakNotaActionPerformed(evt);
            }
        });
        jMenu2.add(menuCetakNota);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Security");

        menuItemUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/child/user.png"))); // NOI18N
        menuItemUser.setText("Management User");
        menuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUserActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemUser);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLapHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapHarianActionPerformed
        // TODO add your handling code here:
        LaporanPenjualanHarian.getPanelLaporanHarian().setName(LaporanPenjualanHarian.PANEL_NAME);
        indexTabs = getComponentIndexByName(LaporanPenjualanHarian.PANEL_NAME);
        if(indexTabs == -1){
            mainTabbedPane.addTab(LaporanPenjualanHarian.PANEL_NAME, LaporanPenjualanHarian.getPanelLaporanHarian());
            setSelectedPanel(LaporanPenjualanHarian.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTabs);
        }
    }//GEN-LAST:event_btnLapHarianActionPerformed

    private void btnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterActionPerformed
        // TODO add your handling code here:
        MasterData.getPanelProduk().setName(MasterData.PANEL_NAME);
        indexTabs = getComponentIndexByName(MasterData.PANEL_NAME);
        if(indexTabs == -1){
            mainTabbedPane.addTab(MasterData.PANEL_NAME, MasterData.getPanelProduk());
            setSelectedPanel(MasterData.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTabs);
        }
    }//GEN-LAST:event_btnMasterActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        PanelPenjualan.getPanelPenjualan().setName(PanelPenjualan.PANEL_NAME);
        indexTabs = getComponentIndexByName(PanelPenjualan.PANEL_NAME);
        if(indexTabs == -1){
            mainTabbedPane.addTab(PanelPenjualan.PANEL_NAME, PanelPenjualan.getPanelPenjualan());
            setSelectedPanel(PanelPenjualan.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTabs);
        }
    }//GEN-LAST:event_btnTransaksiActionPerformed
 
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        mainTabbedPane.removeAll();
        Main.setKasir(null);
        kasir = new Kasir();
        this.dispose();
        Main.initLogin();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLapPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPendapatanActionPerformed
        LaporanPendapatan.getLaporanPendapatan().setName(LaporanPendapatan.PANEL_NAME);
        indexTabs = getComponentIndexByName(LaporanPendapatan.PANEL_NAME);
        if(indexTabs == -1){
            mainTabbedPane.addTab(LaporanPendapatan.PANEL_NAME, LaporanPendapatan.getLaporanPendapatan());
            setSelectedPanel(LaporanPendapatan.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTabs);
        }
    }//GEN-LAST:event_btnLapPendapatanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnTutupActionPerformed

    private void menuCetakNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCetakNotaActionPerformed
        // TODO add your handling code here:
        PanelCetakNota.getPanelCetakNota().setName(PanelCetakNota.PANEL_NAME);
        indexTabs = getComponentIndexByName(PanelCetakNota.PANEL_NAME);
        if(indexTabs == -1){
            mainTabbedPane.addTab(PanelCetakNota.PANEL_NAME, PanelCetakNota.getPanelCetakNota());
            setSelectedPanel(PanelCetakNota.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTabs);
        }
    }//GEN-LAST:event_menuCetakNotaActionPerformed

    private void menuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUserActionPerformed
        // TODO add your handling code here:
        MasterUser.getMasterUserPanel().setName(MasterUser.PANEL_NAME);
        indexTabs = getComponentIndexByName(MasterUser.PANEL_NAME);
        if(indexTabs == -1){
            mainTabbedPane.addTab(MasterUser.PANEL_NAME, MasterUser.getMasterUserPanel());
            setSelectedPanel(MasterUser.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTabs);
        }
    }//GEN-LAST:event_menuItemUserActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Main.initLogin();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLapHarian;
    private javax.swing.JButton btnLapPendapatan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMaster;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnTutup;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JMenuItem menuCetakNota;
    private javax.swing.JMenuItem menuItemUser;
    private javax.swing.JProgressBar progresBar;
    // End of variables declaration//GEN-END:variables
}
